import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import "../globals.css";
import StoryblokProvider from "@/app/(app)/components/StoryblokProvider";
import Image from "next/image";
import Header from "./components/header";

storyblokInit({
  accessToken: "j7Y8xKBF6ZzuqhMP6XIBMQtt",
  use: [apiPlugin],
  apiOptions: {
    region: "en",
  },
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-inter",
});

const mirial = localFont({
  src: [
    {
      path: "../../public/fonts/mirai-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/mirai-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/mirai-thin.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-mirai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html
        lang="en"
        className={`${inter.variable} ${mirial.variable} scroll-smooth antialiased`}
      >
        <body>
          <Header />
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
